name: flutter_guardian
description: A Flutter client for Guardian edge camera.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  video_player: ^2.9.2
  intl: ^0.19.0
  flutter_webrtc: ^0.9.46

flutter:
  uses-material-design: true
  assets:
    - assets/
